[package]
name = "mod_b"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-ffi = { version = "0.5.0", features = ["macros"] }
rubicon = { version = "3.4.9", features = ["import-globals"] }

[workspace]
